### ISSUE TITLE
Before Live running mix commands

### ISSUE THREAD

**Issue by mgwidmann** [nanobox-io/nanobox-engine-elixir#19]
As the docs say, trying to migrate the DB prior to startup, getting this in the web browser:

```
! FAILED TO BEFORE_LIVE1: MIX ECTO.CREATE --QUIET !

Exit
 1

Command
 su - gonano -c "cd /app; siphon --prefix '' -- bash -i -l -c \"mix ecto.create --quiet\""

Output
 [31m[1m** (Mix) Error fetching/updating Git repository: the "git" executable is not available in your PATH. Please install Git on this machine or pass --no-deps-check if you want to run a previously built application on a system without Git.[0m
```

I tried adding `--no-deps-check` but it returns the same error

**Comment by mgwidmann** [comment]
Adding this to my `run.config` fixed this issue:

```
  extra_packages:
    - git
```

**Comment by sanderson** [comment]
@mgwidmann, Thanks for the solution. `git` is available in build containers and is used to pull engines and other dependencies, but it isn't included by default in live "code" containers (containers that get deployed). The `mix ecto.create --quiet` command runs in a `before_live` hook, which runs inside of a live (with no web requests routing to it) code container.

You've identified the correct solution to this problem. If you need `git` in your live runtime, you can add it as an extra_package.

```yaml
run.config:
  engine: elixir
  extra_packages:
    - git
```

**Comment by mgwidmann** [comment]
The point was that mix itself can shell out to git if you have a `git` or `github` dependency, so as part of the build process git is a requirement. Its not being used at runtime.

**Comment by sanderson** [comment]
Gotcha. If it'll never be needed in a live runtime, you could list `git` as a `dev_package`. That way it'll only get installed locally and will be left out of the live environment. Not a huge space saver, but still something.

**Comment by caroso1222** [comment]
It might be irrelevant for the conversation, but this came out as the first result when I googled `(Mix) Error fetching/updating Git repository: the "git" executable...`. 

It turns out I had this in my Dockerfile: `RUN apk del git make gcc`. Simply removing `git` from that command made the trick (thus keeping git in the container).
